[package]
name = "pesde-registry"
version = "0.2.3-rc.3"
edition = "2021"
repository = "https://github.com/pesde-pkg/index"
publish = false

[lints]
workspace = true

[dependencies]
actix-web = "4.10.2"
actix-cors = "0.7.1"
actix-governor = "0.8.0"
dotenvy = "0.15.7"
thiserror = "2.0.12"
tantivy = "0.24.0"
semver = "1.0.26"
jiff = { version = "0.2.12", features = ["serde"] }
futures = "0.3.31"
tokio = "1.44.2"
tokio-util = "0.7.15"
tempfile = "3.19.1"
fs-err = { version = "3.1.0", features = ["tokio"] }
async-stream = "0.3.6"

git2 = "0.20.1"
gix = { version = "0.72.1", default-features = false, features = [
    "blocking-http-transport-reqwest-rust-tls",
    "credentials",
] }

serde = "1.0.219"
serde_json = "1.0.140"
serde_yaml = "0.9.34"
toml = "0.8.22"
convert_case = "0.8.0"
sha2 = "0.10.9"

rusty-s3 = "0.7.0"
reqwest = { version = "0.12.15", default-features = false, features = ["json", "rustls-tls"] }
constant_time_eq = "0.4.2"

tokio-tar = "0.3.1"
async-compression = { version = "0.4.23", features = ["tokio", "gzip"] }

tracing = { version = "0.1.41", features = ["attributes"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tracing-actix-web = "0.7.18"

sentry = { version = "0.37.0", default-features = false, features = ["backtrace", "contexts", "debug-images", "panic", "reqwest", "rustls", "tracing"] }
sentry-actix = "0.37.0"

pesde = { path = "..", default-features = false, features = ["wally-compat"] }
