[package]
name = "pesde-registry"
version = "0.2.3-rc.4"
edition = "2021"
repository = "https://github.com/pesde-pkg/index"
publish = false

[lints]
workspace = true

[dependencies]
actix-web = "4.11.0"
actix-cors = "0.7.1"
actix-governor = "0.8.0"
dotenvy = "0.15.7"
thiserror = "2.0.12"
tantivy = "0.24.2"
semver = "1.0.26"
jiff = { version = "0.2.15", features = ["serde"] }
futures = "0.3.31"
tokio = "1.47.1"
tokio-util = "0.7.16"
tempfile = "3.20.0"
fs-err = { version = "3.1.1", features = ["tokio"] }
async-stream = "0.3.6"

git2 = "0.20.2"
gix = { version = "0.73.0", default-features = false, features = [
    "blocking-http-transport-reqwest-rust-tls",
    "credentials",
] }

serde = "1.0.219"
serde_json = "1.0.142"
serde_yaml = "0.9.34"
toml = "0.9.5"
convert_case = "0.8.0"
sha2 = "0.10.9"

rusty-s3 = "0.8.0"
reqwest = { version = "0.12.22", default-features = false, features = ["json", "rustls-tls"] }
constant_time_eq = "0.4.2"

tokio-tar = "0.3.1"
async-compression = { version = "0.4.27", features = ["tokio", "gzip"] }

tracing = { version = "0.1.41", features = ["attributes"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tracing-actix-web = "0.7.19"

sentry = { version = "0.42.0", default-features = false, features = ["backtrace", "contexts", "debug-images", "panic", "reqwest", "rustls", "tracing"] }
sentry-actix = "0.42.0"

pesde = { path = "..", default-features = false, features = ["wally-compat"] }
