name: Debug

on:
  push:
  pull_request:

env:
  CRATE_NAME: pesde
  BIN_NAME: pesde

jobs:
  get-version:
    name: Get build version
    runs-on: ubuntu-latest
    outputs:
      version: v${{ steps.get_version.outputs.value }}+rev.g${{ steps.trim_sha.outputs.trimmed_sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get package version
        id: get_version
        run: |
          VERSION=$(cargo metadata --format-version 1 --no-deps | jq -r '.packages[] | select(.name == "${{ env.CRATE_NAME }}") | .version')
          echo "value=$VERSION" >> $GITHUB_OUTPUT

      - name: Trim commit SHA
        id: trim_sha
        run: |
          commit_sha=${{ github.sha }}
          echo "trimmed_sha=${commit_sha:0:7}" | tee $GITHUB_OUTPUT
  build:
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            host: linux
            arch: x86_64
            target: x86_64-unknown-linux-gnu

          - runner: ubuntu-24.04-arm
            host: linux
            arch: aarch64
            target: aarch64-unknown-linux-gnu

          - runner: windows-latest
            host: windows
            arch: x86_64
            target: x86_64-pc-windows-msvc

          - runner: macos-15-intel
            host: macos
            arch: x86_64
            target: x86_64-apple-darwin

          - runner: macos-latest
            host: macos
            arch: aarch64
            target: aarch64-apple-darwin
    name: Build for ${{ matrix.host }}-${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    needs: get-version
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Linux build dependencies
        if: ${{ matrix.host == 'linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install libdbus-1-dev pkg-config

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Compile in debug mode
        run: cargo build --bins --no-default-features --features bin,patches --target ${{ matrix.target }} --locked

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.BIN_NAME }}-debug-${{ needs.get-version.outputs.version }}-${{ matrix.host }}-${{ matrix.arch }}
          if-no-files-found: error
          path: |
            target/${{ matrix.target }}/debug/${{ env.BIN_NAME }}.exe
            target/${{ matrix.target }}/debug/${{ env.BIN_NAME }}
